# Generated by Django 4.2.4 on 2023-08-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('dominant', 'Dominant'), ('accent', 'Accent')], max_length=10)),
                ('palette_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.palette')),
            ],
        ),
    ]
