# Generated by Django 4.2.4 on 2023-08-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palette',
            old_name='visibilty',
            new_name='visibility',
        ),
    ]
