# Generated by Django 4.2.4 on 2023-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_favorite_palette_id_alter_favorite_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='palette_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='palette',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
