# Generated by Django 4.2.4 on 2023-08-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_color_palette_id_alter_palette_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='color_name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='palette_id',
            new_name='color_palette_id',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='type',
            new_name='color_type',
        ),
        migrations.RenameField(
            model_name='palette',
            old_name='name',
            new_name='palette_name',
        ),
        migrations.RenameField(
            model_name='palette',
            old_name='owner',
            new_name='palette_owner',
        ),
        migrations.RenameField(
            model_name='palette',
            old_name='visibility',
            new_name='palette_visibility',
        ),
    ]
